main: de.bluewolf.mcplugin.core.Plugin
name: McPluginTemplate
version: '${project.version}'
api-version: 1.18
authors: [ Bluewolf787 ]
description: This is a template for Minecraft Spigot plugins
website: https://bluewolf787.github.io

commands:
  ping:
    description: Get your current ping.